### ISSUE TITLE
Is it an Open project? Can any one contribute?

### ISSUE THREAD

**Issue by coolbrg** [buddhist-uni/buddhist-uni.github.io#12]
Just a curious question. Is it open for contribution?

Thanks.

**Comment by buddhist-uni** [comment]
Sure! What kind of contribution were you thinking of?

**Comment by buddhist-uni** [comment]
To give a bit more: as a one-man operation, I could use help with ... Writing, research, design, data entry, UI, content, IT, ... basically everything! 

So if you, or anyone else, is interested in collaborating, I'd love the help. The best place to start would probably be [sending me an email](mailto:khemarato.bhikkhu@gmail.com) with more information about yourself and your interests, and then we can take it from there.

Thanks.
