### ISSUE TITLE
Consider adding your blog to diff.blog

### ISSUE THREAD

**Issue by diffblog** [buddhist-uni/buddhist-uni.github.io#13]
Hello :wave: :wave:

Over the past decade, we have seen the rise of centralized publishing platforms like Medium.  A lot of self hosted blogs were migrated to these platforms in hope of a bigger audience. Sadly, most of these blogs lost their unique identity and became just another page on them.

Our mission is to fight back against monopolies like Medium and promote independent self hosted blogs like yours. We think the best way to make this happen is by improving the visibility and reach of self hosted blogs. And that's why we built [diff.blog](https://diff.blog).

diff.blog is an aggregator of developer blogs. It was started in 2019 to improve the visibility of self hosted blogs. Whenever you publish a new blog post on your blog, it would automatically appear in the diff.blog news feed. The title and summary of the post would be visible to the users of diff.blog and they can click on the post to read the full post on your blog.

We also have a weekly email digest, which would email the most popular blog posts in our index to all diff.blog users.

diff.blog index over 610 blogs at the moment. And our network is growing steadily every day. And we would like to invite you to include your blog in diff.blog as well.

Adding your blog to diff.blog is super easy and takes less than a minute.
* Go to https://diff.blog
* Sign up with your GitHub account.
* Go to blog settings https://diff.blog/account/settings/blog/
* Add the URL of your blog

We are looking forward to have your blog in diff.blog. Let us know if you have any questions. Happy to answer.

**Comment by buddhist-uni** [comment]
Thanks for the (I assume automated) invitation but I think my blog isn't thematically relevant to your aggregator.
