### ISSUE TITLE
Improved drop-down filters for search

### ISSUE THREAD

**Issue by khemarato** [buddhist-uni/buddhist-uni.github.io#34]
Right now, search supports type filters via a dropdown and other filters via text (e.g. "+is:music"). It would be nice to add:

1. Subcats ("is:poetry", etc) (can maybe be added to the existing dropdown?)
2. Authors (maybe a typeahead dropdown pulling from the _authors collection? Handling hyphens in the filter query will be tricky)
3. Translator (will have to pull this list by looking at the _authors that actually have translated _content. Perhaps can be combined with the author filter above somehow)
4. Rating (e.g. "status: featured" content only) This data would have to be added to the search index first, and then given a dropdown.

**Comment by ColmBhandal** [comment]
However, looks like the build isn't configured for forks. So I'm not sure how to test my changes. Please advise...

**Comment by buddhist-uni** [comment]
Oh! Nice 🙂  To build locally, try:

```bash
npm ci
bash scripts/install-deps.bash
bundle install
bundle exec jekyll serve -tI
```

**Comment by ColmBhandal** [comment]
Unfortunately I can't get it to work. I'm too unfamiliar with the lunr search and how it ties together with the search logic coming from the JS file. My attempt was as follows, in search.js:

```
// Retrieve selected type
		var typeFilter = document.getElementById("search-type-filter");
		var typeFilterValue = typeFilter.value;
		if (typeFilterValue && typeFilterValue !== "") {			
			q += " +is:" + typeFilterValue;
		}

```

The idea being we append "is:<blah>" onto the query if there is some value selected for the dropdown. However, in practice it doesn't seem to work. I'd need some guidance to continue. Or I can just drop the branch if there's nobody available to review, I'm sure it's a pretty minor issue.

**Comment by ColmBhandal** [comment]
OK, I made some progress, but there are a couple of issues that need expert review:

1. The search functionality seems to be OR-based, so adding the `+author:bodhi` for example just appends all content from Bodhi, rather than narrowing down the search. Is this what's expected?
1. I don't think I have permission to create a PR from my fork. Maybe someone can review the fork? https://github.com/ColmBhandal/buddhist-uni.github.io/tree/feature/34-drop-down-filters

Thanks!

**Comment by buddhist-uni** [comment]
Thanks for landing the first PR for this, @ColmBhandal! 🥳 I've updated the description with what's been done and what there's left to do.
