### ISSUE TITLE
Paginate Long Lists

### ISSUE THREAD

**Issue by khemarato** [buddhist-uni/buddhist-uni.github.io#38]
Some of the lists on the site (such as [the list of all articles](https://buddhistuniversity.net/content/articles/)) are quite long and could probably use some pagination. This will require either writing a Jekyll Plugin to create "/page/1" etc for these lists OR will require using a JS library to display the list as a paginated table (I'm currently leaning towards the latter as it will also allow custom sorting)

**Comment by buddhist-uni** [comment]
The search results page could probably be paginated fairly easily, so that may be a good place to start.

**Comment by khemarato** [comment]
For going with the JS approach, let's use the datatables library: https://datatables.net/examples/basic_init/zero_configuration.html

Which should fallback nicely for any users not enabling js
