### ISSUE TITLE
Contributing Guidelines & Dev Env Setup Guidance

### ISSUE THREAD

**Issue by ColmBhandal** [buddhist-uni/buddhist-uni.github.io#76]
Add guidance for newcomers on how to set up a local environment and guidelines on how to contribute. I believe the local build can be done with the following bash commands, after installing Ruby locally:

```
npm ci
bash scripts/install-deps.bash
bundle install
bundle exec jekyll serve -tI
```

See this issue: https://github.com/buddhist-uni/buddhist-uni.github.io/issues/34.

**Comment by buddhist-uni** [comment]
Thanks for the issue!

This is currently documented in the contributing guide located at [CONTRIBUTING.md](https://github.com/buddhist-uni/buddhist-uni.github.io/blob/main/CONTRIBUTING.md) which is linked to from [the main README](https://github.com/buddhist-uni/buddhist-uni.github.io#contributing).

Where were you expecting to find this information?

**Comment by ColmBhandal** [comment]
My bad, how did I not see that!! :)
