### ISSUE TITLE
Using onlick navigation on non-link elements makes for a confusing UX

### ISSUE THREAD

**Issue by zacanger** [buddhist-uni/buddhist-uni.github.io#89]
[Reference code](https://github.com/buddhist-uni/buddhist-uni.github.io/blob/afb9508f24c9e2963ec9a7e021afa6456536a44d/index.html#L20)

Reproduction:
* Cmd or ctrl-click on the actual A element (for example "Courses") inside the Courses `li`, with the intention of opening the link in a new tab
* Note that you now have two tabs on the same page, rather than the default behavior

Possible fixes:
* Don't have the onclick handler at all
* Throw that onClick into a function and check if `e.metaKey || e.ctrlKey` and if _not_, then navigate

I would be happy to put in a PR if a maintainer can let me know what they would prefer.

**Comment by buddhist-uni** [comment]
Ah! I fixed this on the /courses page [three months ago](https://github.com/buddhist-uni/buddhist-uni.github.io/commit/6786289aa3d4fcfe27e3e467585fde0535f8cc7a), but forgot to fix this on the homepage too 🙈  Thank you for the report and especially for linking to the code reference.  Does this fix the bug: https://github.com/buddhist-uni/buddhist-uni.github.io/commit/6b0511276c354221324ca3fed90712e49c05baa8

**Comment by zacanger** [comment]
That change does fix the issue, thank you very much!

**Comment by buddhist-uni** [comment]
Great to hear! Thanks again for taking the time to point it out 😊 Best, KhBh
